services:
  miceco:
    build: .
    container_name: miceco
    environment:
      - TZ=Europe/Berlin
    restart: no
    volumes:
      - ./miceco.cfg:/usr/src/app/miceco.cfg:ro
      - ./ignoredemojis.txt:/usr/src/app/ignoredemojis.txt:ro
